version: "3.9"

services:
  web:
    build: ./flask-app
    ports:
      - "5001:5000"
    volumes:
      - ./flask-app/app:/app
    # depends_on:
    #   - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/algtutor

#   db:
#     image: postgres:16
#     restart: unless-stopped
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: algtutor
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: